[package]
name = "cdr-remote-agent"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
cdr-core.workspace = true
cdr-remote-protocol.workspace = true
chrono.workspace = true
futures-util.workspace = true
hex.workspace = true
regex.workspace = true
reqwest.workspace = true
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
similar.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
cdr-windows-native = { path = "../cdr-windows-native" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
