from codex_desktop_bridge_impl_type_exports import *  # noqa: F403

def _read_ipc_response(handle: int, request_id: str, timeout_sec: float, owner_clients: dict[str, str]) -> JsonObject: ...
def _request_start_turn_via_ipc(handle: int, source_client_id: str, thread: ThreadInfo, prompt: str, timeout_sec: float, owner_clients: dict[str, str]) -> dict[str, str]: ...
def _write_ipc_message(handle: int, message: JsonObject) -> None: ...
