from __future__ import annotations

from collections.abc import Mapping

MODULE_ALIASES: Mapping[str, str] = {
    "discord_commands": "codex_discord_commands",
    "discord_context": "codex_discord_context",
    "discord_help": "codex_discord_help",
    "discord_interactive": "codex_discord_interactive",
    "discord_mirror_status": "codex_discord_mirror_status",
    "discord_projects": "codex_discord_projects",
    "discord_thread_state": "codex_discord_thread_state",
    "windows_harness": "codex_windows_harness",
}

EXPORTS_BY_MODULE: Mapping[str, tuple[str, ...]] = {
    "codex_discord_attachments": (
        "DISCORD_ATTACHMENT_MAX_BYTES_DEFAULT",
        "DISCORD_ATTACHMENT_TEXT_INLINE_MAX_BYTES_DEFAULT",
        "DISCORD_ATTACHMENT_TEXT_PREVIEW_CHARS",
        "TEXT_ATTACHMENT_EXTENSIONS",
        "discord_attachments_enabled",
        "get_attachment_size",
        "get_discord_attachment_max_bytes",
        "get_discord_attachment_text_inline_max_bytes",
        "get_message_attachment_dir",
        "is_text_attachment",
        "message_has_non_text_payload",
        "read_attachment_text_preview",
        "sanitize_attachment_filename",
        "save_discord_attachment",
    ),
    "codex_discord_busy": ("has_busy_choice_source", "is_selected_thread_busy_error", "log_busy_choice_sent"),
    "codex_discord_button_qa_interactions": (
        "SyntheticQAFollowup",
        "SyntheticQAInteraction",
        "SyntheticQAResponse",
    ),
    "codex_discord_components": (
        "APPROVAL_CUSTOM_ID_PREFIX",
        "BUSY_CHOICE_CUSTOM_ID_PREFIX",
        "INPUT_CHOICE_CUSTOM_ID_PREFIX",
        "format_approval_custom_id",
        "format_busy_choice_custom_id",
        "format_input_choice_custom_id",
        "get_busy_choice_custom_ids_from_message",
        "get_component_children",
        "get_persistent_component_claim_key",
        "is_safe_persistent_input_value",
        "parse_approval_custom_id",
    ),
    "codex_discord_context": (
        "format_rate_limit_line",
        "format_rate_limit_reset",
        "format_window_minutes",
        "parse_event_timestamp",
    ),
    "codex_discord_context_refresh": (
        "extract_context_refresh_item",
        "parse_session_event_timestamp",
        "truncate_context_refresh_text",
    ),
    "codex_discord_delivery": ("build_delivery_id", "get_interaction_command_name", "get_messageable_id"),
    "codex_discord_diagnostics": (
        "format_discord_id_list",
        "format_discord_message_created_at",
        "format_discord_message_type",
        "resolve_discord_history_channel",
    ),
    "codex_discord_empty_content_notice": ("should_send_empty_content_notice",),
    "codex_discord_interaction_gate": ("is_discord_user_allowed",),
    "codex_discord_interaction_log": (
        "format_discord_user_id_for_log",
        "format_interaction_type",
        "format_raw_interaction_command",
        "get_interaction_custom_id",
    ),
    "codex_discord_interactive": ("infer_interactive_state_from_error", "normalize_interactive_text_reply"),
    "codex_discord_logging": (
        "get_log_field",
        "get_log_path",
        "is_user_or_control_hook_summary",
        "parse_log_line",
        "summarize_discord_hook_log_line",
    ),
    "codex_discord_message_gate": (
        "DEFAULT_PLAIN_ASK_CONTEXT_KEYWORDS",
        "DISCORD_USER_MENTION_RE",
        "get_bridge_mention_user_ids",
        "get_discord_message_mention_ids",
        "get_plain_ask_context_keywords",
        "is_bot_authored_bridge_mention",
        "message_mentions_bridge_user",
        "message_mentions_other_bot",
        "message_mentions_required_plain_ask_user",
        "plain_ask_context_fallback_enabled",
        "plain_ask_context_matches",
        "should_accept_plain_ask_without_required_mention",
        "strip_required_plain_ask_mentions",
    ),
    "codex_discord_mirror_names": (
        "get_mirror_project_channel_name",
        "get_mirror_thread_name",
        "normalize_discord_name",
        "truncate_discord_title",
    ),
    "codex_discord_mirror_orphans": ("cleanup_orphan_discord_threads",),
    "codex_discord_mirror_project_channels": ("find_existing_project_channel",),
    "codex_discord_mirror_scope": ("bounded_mirror_limit",),
    "codex_discord_mirror_sync_result": ("empty_mirror_cleanup_result",),
    "codex_discord_mirror_thread_channels": ("ensure_mirror_thread_channel", "find_existing_thread_channel"),
    "codex_discord_origin_prompts": ("make_discord_origin_prompt_digest",),
    "codex_discord_persistent_busy_choice": ("make_persistent_busy_source_message",),
    "codex_discord_prefix_skill_prompts": (
        "DEEP_INTERVIEW_PROMPT_HEADER",
        "build_deep_interview_prompt",
    ),
    "codex_discord_prompt_busy_result": ("build_codex_app_busy_retry_message",),
    "codex_discord_prompt_pending_delivery": ("format_pending_ask_delivery_output",),
    "codex_discord_projects": (
        "find_projectless_new_chat_cwd",
        "get_saved_workspace_project_keys",
        "is_codex_projectless_chat_cwd",
        "is_thread_mirrorable",
    ),
    "codex_discord_queue_messages": ("build_retract_message",),
    "codex_discord_runtime": ("get_codex_app_turn_condition", "normalize_runner_key"),
    "codex_discord_runtime_config": (
        "discord_qa_commands_enabled",
        "discord_stream_commentary_enabled",
        "get_ask_busy_retry_attempts",
        "get_required_env",
        "get_stale_busy_steer_block_seconds",
        "load_local_env",
    ),
    "codex_discord_session_mirror": (
        "format_session_mirror_text",
        "has_recent_session_text",
        "make_session_mirror_event_digest",
        "make_text_digest",
        "remember_recent_session_text",
    ),
    "codex_discord_session_mirror_output_targets": ("cleanup_active_session_mirror_output_targets",),
    "codex_discord_socket_event_log": ("claim_socket_event_log", "get_socket_event_log_key"),
    "codex_discord_stale_busy_components": ("has_active_busy_choice_custom_id",),
    "codex_discord_steering": ("make_steering_prompt_result",),
    "codex_discord_store": (
        "cleanup_processed_discord_messages",
        "cleanup_session_mirror_events",
        "create_busy_choice_record",
        "find_mirror_project_row_by_key",
        "get_session_mirror_offset",
        "get_session_mirror_targets",
    ),
    "codex_discord_text": (
        "extract_prompt_first_sentence",
        "format_percent",
        "parse_bounded_int_arg",
        "parse_int_set",
        "split_message",
    ),
    "codex_discord_ui_ask": ("build_ui_ask_argv", "should_retry_ask_with_ui"),
    "codex_discord_bridge_process": ("build_bridge_subprocess_env", "parse_bridge_output_value"),
}
