from __future__ import annotations

from typing import Protocol

from codex_desktop_bridge_archive_retry import archive_thread_once as archive_thread_once
from codex_desktop_bridge_impl_common import *
from codex_desktop_bridge_ipc_runtime import OwnerClients
from codex_desktop_bridge_sidecar_resolver import detect_running_codex_app_server_executable as detect_running_codex_app_server_executable
from codex_thread_models import ThreadContextUsage, ThreadInfo as ThreadInfo, WindowInfo

class Incomplete(Protocol):
    pass

def typed_choose_or_resolve_thread_from_args(args: argparse.Namespace) -> ThreadInfo: ...
def typed_choose_thread_from_args(args: argparse.Namespace) -> ThreadInfo: ...
def typed_close_ipc_pipe(handle: int) -> None: ...
def typed_discover_owner_client_for_thread(handle: int, thread_id: str, timeout_sec: float) -> str | None: ...
def typed_extract_thread_snapshot_from_ipc_message(message: JsonObject, thread_id: str) -> tuple[JsonObject, str] | None: ...
def typed_initialize_ipc_client(handle: int, owner_clients: dict[str, str], timeout_sec: float = 3.0) -> str: ...
def typed_make_final_answer_watch_deps() -> final_answer_watch.FinalAnswerWatchDeps: ...
def typed_make_ipc_runtime_deps() -> ipc_runtime.IpcRuntimeDeps: ...
def typed_make_new_command_deps() -> new_command.NewCommandDeps: ...
def typed_make_pending_reply_deps() -> bridge_reply.PendingReplyDeps: ...
def typed_make_prompt_sender_deps() -> prompt_sender.PromptSenderDeps: ...
def typed_open_codex_ipc_pipe() -> int: ...
def typed_read_ipc_message(handle: int, timeout_sec: float) -> JsonObject: ...
def typed_record_owner_client_from_ipc_message(message: JsonObject, owner_clients: OwnerClients) -> None: ...
def typed_request_start_turn_via_ipc(handle: int, source_client_id: str, thread: ThreadInfo, prompt: str, timeout_sec: float, owner_clients: dict[str, str]) -> dict[str, str]: ...
def _read_ipc_response(handle: int, request_id: str, timeout_sec: float, owner_clients: dict[str, str]) -> JsonObject: ...
def _request_start_turn_via_ipc(handle: int, source_client_id: str, thread: ThreadInfo, prompt: str, timeout_sec: float, owner_clients: dict[str, str]) -> dict[str, str]: ...
def _write_ipc_message(handle: int, message: JsonObject) -> None: ...
def activate_thread_by_sidebar_v2(thread_name: str, project_name: str | None = None) -> str: ...
def verify_active_thread(thread_id: str) -> str | None: ...
def verify_active_thread_by_header(thread_name: str) -> str | None: ...
def wait_for_thread_activation(thread: ThreadInfo, thread_name: str, timeout_sec: float = 5.0) -> str | None: ...
def activate_thread_in_ui(thread: ThreadInfo) -> str: ...
def archive_thread_with_lock_retry(thread_id: str, *, kill_codex_on_lock: bool) -> None: ...
def build_parser() -> argparse.ArgumentParser: ...
def build_approval_decision_payload(answer_text: str) -> tuple[str, str]: ...
def build_interactive_notice_from_function_call(payload: JsonObject) -> str: ...
def build_reply_input_response_payload(pending_request: JsonObject, answer_text: str) -> tuple[JsonObject, dict[str, list[str]]]: ...
def build_workspace_ref_map(threads: list[ThreadInfo]) -> dict[str, str]: ...
def cache_live_approval_request(pending_request: JsonObject) -> None: ...
def cancel_codex_reply_if_busy(timeout_sec: float = 3.0) -> tuple[list[str], list[str]]: ...
def check_codex_app_update() -> doctor_report.CodexAppUpdateStatus: ...
def choose_thread(thread_id: str | None, cwd: str | None) -> ThreadInfo: ...
def clear_cached_live_approval_request(thread_id: str) -> None: ...
def click_window(window: WindowInfo, x_ratio: float, y_offset: int) -> tuple[int, int]: ...
def collapse_list_text(value: str, limit: int = 70) -> str: ...
def command_archived_list(args: argparse.Namespace) -> int: ...
def command_approval_reply(args: argparse.Namespace) -> int: ...
def command_archive(args: argparse.Namespace) -> int: ...
def command_ask(args: argparse.Namespace) -> int: ...
def command_delete_archive(args: argparse.Namespace) -> int: ...
def command_discover_codex(_args: argparse.Namespace) -> int: ...
def command_doctor(args: argparse.Namespace) -> int: ...
def command_focus(args: argparse.Namespace) -> int: ...
def command_list(args: argparse.Namespace) -> int: ...
def command_new(args: argparse.Namespace) -> int: ...
def command_open(args: argparse.Namespace) -> int: ...
def command_restart_codex(args: argparse.Namespace) -> int: ...
def command_settings(args: argparse.Namespace) -> int: ...
def command_settings_options(args: argparse.Namespace) -> int: ...
def command_status(args: argparse.Namespace) -> int: ...
def command_stop(args: argparse.Namespace) -> int: ...
def command_tail(args: argparse.Namespace) -> int: ...
def command_use(args: argparse.Namespace) -> int: ...
def describe_thread_busy_state(state: str) -> str: ...
def describe_thread_context_usage(context_usage: ThreadContextUsage) -> str: ...
def detect_running_codex_desktop_executable() -> tuple[Path | None, str]: ...
def discover_codex_desktop_executable() -> tuple[Path | None, str]: ...
def ensure_codex_composer_focus(attempts: int = 4) -> bool: ...
def ensure_codex_desktop_executable_configured() -> tuple[Path, str, bool]: ...
def extract_message_text(payload: JsonObject) -> str: ...
def find_codex_window() -> WindowInfo: ...
def focus_window(window: WindowInfo) -> None: ...
def format_thread_model_display(thread: ThreadInfo, mode: str, speed: str) -> str: ...
def format_timestamp(unix_seconds: int) -> str: ...
def format_title_preview(value: str, limit: int = 120) -> str: ...
def format_token_k(value: int) -> str: ...
def get_busy_threads(limit: int = 50) -> list[ThreadInfo]: ...
def get_cached_live_approval_request(thread_id: str, *, max_age_sec: float = 120.0) -> JsonObject | None: ...
def get_clipboard_text() -> str | None: ...
def get_high_context_threads(limit: int = 20) -> list[tuple[ThreadInfo, ThreadContextUsage]]: ...
def get_last_user_and_assistant_messages(session_path: Path) -> tuple[str, str]: ...
def get_live_pending_approval_display_lines(thread: ThreadInfo, *, timeout_sec: float = 1.0, reason_limit: int = 160) -> tuple[str | None, list[str]]: ...
def get_pending_approval_request_via_ipc(thread: bridge_pending.PendingThread, timeout_sec: float = 6.0) -> JsonObject | None: ...
def get_pending_interactive_display_lines(session_path: Path, *, recent_limit: int = 256) -> tuple[str | None, list[str]]: ...
def get_pending_interactive_summary(session_path: Path, *, limit: int = 100) -> str: ...
def get_pending_permission_approval_from_session(session_path: Path, *, recent_limit: int = 256) -> JsonObject | None: ...
def get_pending_user_input_request_via_ipc(thread: bridge_pending.PendingThread, timeout_sec: float = 6.0) -> JsonObject | None: ...
def get_saved_thread_settings(thread_id: str) -> dict[str, str]: ...
def get_selected_thread_id() -> str | None: ...
def get_thread_busy_state(thread: busy_state.BusyThread, *, client: busy_state.SidecarClient | None = None, allow_resume: bool = False) -> str: ...
def get_thread_collaboration_mode(thread: ThreadInfo) -> str: ...
def get_thread_context_usage(thread: ThreadInfo) -> ThreadContextUsage | None: ...
def get_thread_label(thread: ThreadInfo) -> str: ...
def get_thread_service_tier(thread: ThreadInfo) -> str: ...
def get_thread_slot(thread: ThreadInfo, limit: int = 9) -> int | None: ...
def get_thread_ui_name(thread_id: str, thread: ThreadInfo | None = None) -> str | None: ...
def get_thread_ui_name_candidates(thread: ThreadInfo) -> list[str]: ...
def get_thread_workspace_name(thread: ThreadInfo) -> str: ...
def get_thread_workspace_ref(thread: ThreadInfo, threads: list[ThreadInfo] | None = None) -> str: ...
def is_protocol_registered(protocol: str) -> bool: ...
def is_thread_busy(session_path: Path) -> bool: ...
def load_archived_threads(limit: int = 20) -> list[ThreadInfo]: ...
def load_ordinary_user_root_threads(limit: int = 0) -> list[ThreadInfo]: ...
def load_recent_threads(limit: int = 20) -> list[ThreadInfo]: ...
def load_user_root_threads(limit: int = 0) -> list[ThreadInfo]: ...
def make_console_safe_text(value: str | None) -> str: ...
def make_cli_handlers() -> bridge_cli.BridgeCommandHandlers: ...
def print_thread_list(threads: list[ThreadInfo]) -> None: ...
def read_new_session_events(session_path: Path, start_offset: int, *, max_events: int | None = None) -> tuple[list[JsonObject], int]: ...
def remember_thread_settings(thread_id: str, *, model: str | None, reasoning: str | None, speed: str | None) -> None: ...
def reply_to_pending_approval(thread: bridge_reply.ReplyThread, answer_text: str, timeout_sec: float = 6.0) -> bridge_reply.ReplyResult: ...
def resolve_archived_thread_ref(thread_ref: str, limit: int = 100) -> ThreadInfo: ...
def resolve_new_thread_cwd(cwd: str | None) -> str: ...
def resolve_thread_ref(thread_ref: str, limit: int = 50) -> ThreadInfo: ...
def rotate_single_backup_file(path: Path, *, max_bytes: int = 512000, incoming_bytes: int = 0) -> None: ...
def send_hotkey(*keys: int) -> None: ...
def send_key_event(vk: int, keyup: bool = False) -> None: ...
def send_prompt_to_codex(prompt: str, click_x_ratio: float, click_y_offset: int, skip_click: bool) -> WindowInfo: ...
def set_clipboard_text(text: str) -> None: ...
def set_selected_thread_id(thread_id: str | None) -> None: ...
def should_recommend_archive(thread: ThreadInfo, context_usage: ThreadContextUsage | None) -> bool: ...
def snapshot_recent_session_offsets(limit: int = 10, include_threads: list[ThreadInfo] | None = None) -> prompt_delivery.SessionOffsets: ...
def spawn_background_new_thread_runner(prompt: str, cwd: str) -> subprocess.Popen[bytes]: ...
def start_background_watch(thread: ThreadInfo, start_offset: int, timeout_sec: float, include_commentary: bool, stream_output: bool) -> bool: ...
def start_codex_desktop_process(executable_path: Path) -> subprocess.Popen[str]: ...
def start_turn_via_ipc(thread: ThreadInfo, prompt: str, timeout_sec: float = 4.0, *, allow_ui_recovery: bool = False) -> dict[str, str]: ...
def start_turn_via_sidecar(thread: ThreadInfo, prompt: str, *, timeout_sec: float = 10.0, keep_client_open: bool = False) -> sidecar_thread.StartTurnResult: ...
def stop_codex_archive_lock_candidates() -> list[str]: ...
def stop_codex_desktop_processes(executable_path: Path) -> tuple[bool, str]: ...
def submit_approval_decision_via_ipc(thread: ipc_turn.IpcThread, request_id: JsonValue, decision_payload: JsonValue, request_kind: str, timeout_sec: float = 6.0, *, use_target_client: bool = True) -> JsonObject: ...
def submit_permission_approval_via_ui_row_select(answer_text: str) -> bridge_reply.ReplyResult: ...
def submit_user_input_via_ipc(thread: ipc_turn.IpcThread, request_id: str, response_payload: JsonObject, timeout_sec: float = 6.0) -> JsonObject: ...
def summarize_interactive_lines(state: str | None, lines: list[str], *, limit: int = 100) -> str: ...
def sync_session_index_with_state() -> int: ...
def verify_thread_in_ui(thread: ThreadInfo) -> str | None: ...
def wait_for_new_thread(previous_ids: set[str], timeout_sec: float = 8.0) -> ThreadInfo | None: ...
def wait_for_prompt_delivery(session_offsets: prompt_delivery.SessionOffsets, prompt: str, timeout_sec: float = 4.0) -> ThreadInfo | None: ...
def wait_for_thread_record(thread_id: str, *, archived: bool | None = None, timeout_sec: float = 8.0) -> tuple[ThreadInfo, bool] | None: ...
def watch_for_final_answer(session_path: Path, start_offset: int, timeout_sec: float, include_commentary: bool, stream_live: bool = False, stream_label: str = '', stream_callback: Callable[[str], None] | None = None) -> final_answer_watch.WatchForFinalAnswerResult: ...
