from __future__ import annotations

from pathlib import Path
from typing import Protocol

import codex_discord_stream as discord_stream
from codex_session_events import JsonEvent, JsonValue
from codex_thread_models import ThreadContextUsage, ThreadInfo


class CodexBridgeThreadLists(Protocol):
    def load_user_root_threads(self) -> list[ThreadInfo]: ...
    def load_recent_threads(self, limit: int = 20) -> list[ThreadInfo]: ...


class CodexBridgeMirrorStatusModule(Protocol):
    def choose_thread(self, thread_id: str, cwd: str | None) -> ThreadInfo: ...
    def get_thread_context_usage(self, thread: ThreadInfo) -> ThreadContextUsage | None: ...
    def describe_thread_context_usage(self, context_usage: ThreadContextUsage) -> str: ...
    def should_recommend_archive(
        self,
        thread: ThreadInfo,
        context_usage: ThreadContextUsage | None,
    ) -> bool: ...
    def get_thread_collaboration_mode(self, thread: ThreadInfo) -> str: ...
    def get_thread_service_tier(self, thread: ThreadInfo) -> str: ...
    def format_thread_model_display(self, thread: ThreadInfo, mode: str, speed: str) -> str: ...
    def load_recent_threads(self, limit: int = 20) -> list[ThreadInfo]: ...
    def get_thread_ui_name(self, thread_id: str, thread: ThreadInfo | None = None) -> str | None: ...


class CodexBridgePendingInputReplyModule(Protocol):
    def choose_thread(self, thread_id: str | None, cwd: str | None) -> ThreadInfo: ...
    def reply_to_pending_user_input(
        self,
        thread: ThreadInfo,
        answer_text: str,
        timeout_sec: float = 6.0,
    ) -> dict[str, JsonValue]: ...
    def get_thread_workspace_ref(self, thread: ThreadInfo) -> str: ...


class CodexBridgeSelectedThreadModule(Protocol):
    def set_selected_thread_id(self, thread_id: str | None) -> None: ...


class CodexBridgeSessionStateModule(Protocol):
    def sync_session_index_with_state(self) -> int: ...
    def load_recent_threads(self, limit: int = 20) -> list[ThreadInfo]: ...
    def get_selected_thread_id(self) -> str | None: ...
    def choose_thread(self, thread_id: str | None, cwd: str | None) -> ThreadInfo: ...
    def set_selected_thread_id(self, thread_id: str | None) -> None: ...
    def get_thread_workspace_ref(
        self,
        thread: ThreadInfo,
        threads: list[ThreadInfo] | None = None,
    ) -> str: ...
    def get_thread_workspace_name(self, thread: ThreadInfo) -> str: ...


class CodexBridgeFinalAnswerModule(Protocol):
    @property
    def watch_for_final_answer(self) -> discord_stream.WatchForFinalAnswerFunc: ...


class CodexBridgeSessionMirrorEventModule(Protocol):
    def choose_thread(self, thread_id: str | None, cwd: str | None) -> ThreadInfo: ...
    def get_thread_context_usage(self, thread: ThreadInfo) -> ThreadContextUsage | None: ...
    def should_recommend_archive(
        self,
        thread: ThreadInfo,
        context_usage: ThreadContextUsage | None,
    ) -> bool: ...
    def is_thread_busy(self, session_path: Path) -> bool: ...
    def read_new_session_events(
        self,
        session_path: Path,
        start_offset: int,
        *,
        max_events: int | None = None,
    ) -> tuple[list[JsonEvent], int]: ...


class CodexBridgeContextRefreshModule(Protocol):
    def build_interactive_notice_from_function_call(self, payload: dict[str, JsonValue]) -> str: ...
    def extract_message_text(self, payload: dict[str, JsonValue]) -> str: ...
    def choose_thread(self, thread_id: str | None, cwd: str | None) -> ThreadInfo: ...
    def get_thread_workspace_ref(
        self,
        thread: ThreadInfo,
        threads: list[ThreadInfo] | None = None,
    ) -> str: ...
    def get_thread_ui_name(self, thread_id: str, thread: ThreadInfo | None = None) -> str | None: ...
    def normalize_prompt_text(self, value: str) -> str: ...


class CodexBridgeStaleBusySteerModule(Protocol):
    def choose_thread(self, thread_id: str | None, cwd: str | None) -> ThreadInfo: ...
    def is_thread_busy(self, session_path: Path) -> bool: ...
    def get_pending_interactive_state_from_session(self, session_path: Path) -> str | None: ...
    def session_file_age_seconds(self, session_path: Path) -> float | None: ...
    def get_thread_workspace_ref(self, thread: ThreadInfo) -> str: ...
