#[path = "../tests/support/action_app_server.rs"]
pub(crate) mod app_fixture;
#[path = "../tests/support/approval_app_server.rs"]
pub(crate) mod approval_app_fixture;
#[path = "../tests/support/approval_http.rs"]
pub(crate) mod approval_http;
#[path = "../tests/support/approval_owner.rs"]
pub(crate) mod approval_owner;
pub(crate) mod cleanup_refusal_transport;
#[path = "completion_worker/goal_mirror_http.rs"]
pub(crate) mod http_gate;
#[path = "../tests/support/mapped_slash.rs"]
pub(crate) mod mapped_slash;
pub(crate) mod message_fixture;
pub(crate) mod new_reply_fixture;
#[path = "../tests/support/pro_connection.rs"]
pub(crate) mod pro_connection;
pub(crate) mod pro_fixture;
#[path = "../tests/support/pro_plugins.rs"]
pub(crate) mod pro_plugins;
pub(crate) use crate::soak::native_fixture;
